version: "3.8"
services:
    bot:
        build: .
        stop_signal: SIGINT
        restart: unless-stopped
        env_file:
            - ".env"
        volumes:
            - ".env:/app/.env"
            # Если хотите переопределить локализацию, подложите нужный каталог
            # - "/your/path/to/locales:/app/bot/locales"
            # Или даже так:
            # - "/your/custom/language:/app/bot/locales/ru"
        depends_on:
            - db
    db:
        image: postgres:16.1
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dev
        volumes:
            - dbdata:/data/db


volumes:
    dbdata: